Rewrite of /status endpoint
slothpixel/core pull request #668
Opened 2021-07-07 08:24 UTC by TheMysterys

Changes for rewrite stated in #667

2021-07-07 23:13 UTC, Richienb requested changes

2021-07-07 23:13 UTC, Richienb commented on processors/processPlayerStatus.js
> +    mode: mode === 'LOBBY' ? 'Lobby' : (getMode(type, mode)? getMode(type, mode).name || getMode(type, mode) : null),
```suggestion
    mode: mode === 'LOBBY' ? 'Lobby' : (getMode(type, mode) ? getMode(type, mode).name || getMode(type, mode) : null),
```

2021-07-07 23:13 UTC, Richienb commented on processors/processPlayerStatus.js
> +		(modeObject) => modeObject.key === "DREAMS" || modeObject.key === "lab"
```suggestion
		({key}) => key === "DREAMS" || key === "lab"
```

2021-07-07 23:38 UTC, TheMysterys commented
Hold review for a bit, going to try rewrite the getMode() function a bit since some test cases seem to be causing an issue

2021-07-08 00:22 UTC, TheMysterys commented
Okay at current stage code seems stable for use. (Still requiring update of Hypixel Constants https://github.com/slothpixel/hypixelconstants/pull/21 for missing modes to be shown)

2021-07-09 14:18 UTC, builder-247 reviewed
Can you run `npm run lint` and fix the issues there?

2021-07-09 14:33 UTC, builder-247 commented
Also I updated the hypixelconstants package so you can update it in this PR

2021-07-13 00:25 UTC, builder-247 approved these changes

2021-07-13 04:43 UTC, Richienb requested changes

2021-07-13 04:43 UTC, Richienb commented on processors/processPlayerStatus.js
> +// Constant Values for maps and game types
I don't think this comment is nessessary

2021-07-13 04:43 UTC, Richienb commented on processors/processPlayerStatus.js
> +  const gameObject = modes.find((modeObject) => modeObject.key === type);
```suggestion
  const gameObject = modes.find(({key}) => key === type);
```

2021-07-13 04:43 UTC, Richienb commented on processors/processPlayerStatus.js
> +    keys ? keys.includes(mode) || key === mode : key === mode
```suggestion
    (keys && keys.includes(mode)) || key === mode
```

2021-07-13 04:44 UTC, Richienb commented on processors/processPlayerStatus.js
> +    keys ? keys.includes(mode) || key === mode : key === mode
Can also be done for the arrow function after this

2021-07-13 13:24 UTC, Richienb requested changes

2021-07-13 13:24 UTC, Richienb commented on processors/processPlayerStatus.js
> +  return gameObject.modes.find(({key,keys}) =>
```suggestion
  return gameObject.modes.find(({key, keys}) =>
```

2021-07-13 13:24 UTC, Richienb commented on processors/processPlayerStatus.js
> +  let gameObject = modes.find(({key}) => key === type);
```suggestion
  const gameObject = modes.find(({key}) => key === type);
```

2021-07-13 13:24 UTC, Richienb commented on processors/processPlayerStatus.js
> +  let subGameObject = gameObject.modes.find(
```suggestion
  const subGameObject = gameObject.modes.find(
```

Maybe these variables can just be called `game` and `subGame`

2021-07-14 12:30 UTC, Richienb approved these changes

2021-07-14 12:49 UTC, merged